# Site settings
email: olexiy@hawaii.edu
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Alex's Page
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: Alex Dvornikov
profile_img: /images/Portrait.jpg
profile: Hey, there. I’m Alex. I'm a university lecturer. I did a postdoc at UCSF in radiology and a PhD at UH Manoa on neutrinos and dark matter. I am experienced in software and hardware and have written experimental and theoretical papers. I love physics education, fundamental research in particle physics, &amp; medical physics. Send me an <a href="mailto:olexiy@hawaii.edu?Subject=Hello,%20Alex!">email</a>.
social:
  github: https://github.com/alexdvornikov/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
kramdown:
   math_engine: mathjax
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
